### ISSUE TITLE
Error compiling emptiness when compiling HelloWorld spatial program

### ISSUE THREAD

**Issue by hecmay** [stanford-ppl/spatial-multiverse#2]
I am following the instructions in temp_f1.md. When trying to compile the HelloSpatial program on AWS, I got the following error 
```shell
[info] Running HelloSpatial --name HelloSpatial --synth --fpga=AWS_F1
[warn] Area model file AWS_F1_Area.csv for target AWS_F1 was missing expected fields: 
[warn] BRAM
[info] Compiling HelloSpatial to /home/centos/spatial-multiverse/spatial/gen/HelloSpa$
ial/
[bug] An exception was encountered while compiling HelloSpatial: 
[bug]   Error compiling emptiness
[bug]   java.lang.Exception: Error compiling emptiness
[bug] This is due to a compiler bug. A log file has been created at: 
[bug]   /home/centos/spatial-multiverse/spatial/logs/HelloSpatial//HelloSpatial_excep$
ion.log
[failed] Total time: 0.6870 seconds
```

I am using exactly the same version of AMI and aws-fpga as suggested in the MD.

**Comment by mattfel1** [comment]
Hi.  Can you go `/home/centos/spatial-multiverse/spatial//poly/resources` and try `gcc emptiness.c -lisl -o emptiness`?  If this fails, we can work through the error by tinkering with the isl installation.  If it works, can you try `mv emptiness ~/bin`?  You can also move it to any directory on your path.  If ~/bin doesn't exist, spatial is supposed to create it and append it to your PATH.  Let me know which part goes wrong.

**Comment by hecmay** [comment]
Thanks! @mattfel1 that worked after I compiled `emptiness` manually and move it to PATH. It complained that it cannot find the libisl.so. After I set up LB_LIBRARY_PATH correctly, it is working now. 

```shell
[warn] Area model file AWS_F1_Area.csv for target AWS_F1 was missing expected fields: 
[warn] BRAM
[info] Compiling HelloSpatial to /home/centos/spatial/gen/HelloSpatial/
/home/centos/bin/emptiness: error while loading shared libraries: libisl.so.15: cannot open shared object file:
 No such file or directory
[warn] Unsure if emptiness needs to be recompiled... Recompiling to be safe
[bug] An exception was encountered while compiling HelloSpatial: 
[bug]   Error compiling emptiness
[bug]   java.lang.Exception: Error compiling emptiness
[bug] This is due to a compiler bug. A log file has been created at: 
[bug]   /home/centos/spatial/logs/HelloSpatial//HelloSpatial_exception.log
[failed] Total time: 0.7140 seconds
```

**Comment by hecmay** [comment]
However, the `make aws-F1` does not run. I need to do some more research on it...

```shell
[info] Resolved  dependencies
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scalatest:scalatest_2.12:2.2.5
[error]   Not found
[error]   Not found
[error]   not found: /home/centos/.ivy2/local/org.scalatest/scalatest_2.12/2.2.5/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/2.2.5/scalatest_2.12-2.2.5.po$
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scalatest/scalatest_2.12/2.2.$
/scalatest_2.12-2.2.5.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/org/scalatest/scalatest_2.12/2.2.5/
scalatest_2.12-2.2.5.pom
[error] Error downloading org.scalacheck:scalacheck_2.12:1.12.4
```

**Comment by hecmay** [comment]
I manually changed the dependency version in sbt.build. and it is working now. Thanks for your help！

**Comment by yrq0208** [comment]
> I manually changed the dependency version in sbt.build. and it is working now. Thanks for your help！

Hi @hecmay , could you please elaborate exactly what you have changed in the build.sbt file? I think I have run into the same issue when trying to compile resnet50 with zcu102.

**Comment by hecmay** [comment]
@yrq0208 sorry. it's been a long time. I do not remember what I've changed. But I guess you can probably change to any version listed in this folder: https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/
